;====================> 读取配置 <====================;
IniRead, num, .\include\my.ini,section,num
IniRead, id, .\include\my.ini,section1,id
IniRead, all, .\include\my.ini,section2,all
IniRead, pageNum, .\include\my.ini,section3,pageNum
IniRead, maxId, .\include\my.ini,section4,maxId
IniRead, maxNum, .\include\my.ini,section5,maxNum
IniRead, latest_c_time, .\include\my.ini,section6,latest_c_time
IniRead, oldest_c_time, .\include\my.ini,section7,oldest_c_time
IniRead, latest_m_time, .\include\my.ini,section8,latest_m_time
IniRead, oldest_m_time, .\include\my.ini,section9,oldest_m_time
IniRead, latest_u_time, .\include\my.ini,section10,latest_u_time
IniRead, oldest_u_time, .\include\my.ini,section11,oldest_u_time
IniRead, book_jsdx_id, .\include\my.ini,section12,book_jsdx_id
IniRead, book_zgrm_id, .\include\my.ini,section13,book_zgrm_id
IniRead, book_modify_num, .\include\my.ini,section14,book_modify_num
IniRead, book_modify_id, .\include\my.ini,section15,book_modify_id
IniRead, last_title, .\include\my.ini,section16,last_title